travis:
  secure:
    BINSTAR_TOKEN: Pdo6N70/zsK9GGrBlpMciNp60CcV2LjQ27DwvJCaxF6zFX5Yoc8mTiNLHLpdHblA5deGNVigZUsYR8bCc7IXCSzORIcilAJ0OSmVRnYCJYKjR6SFVu3EAmic6mgmgG9hQDOy2S8gBhTi6/BSgI4fN+i1Oj78Z6Apy/Uj71sruZeategTUyUgsgeoQRc/BXBwH0S92E6NJkGm/GGuFYhXxeJvflpYLevjhwdPTJWJQ2GeSWl+TqU0Sz6QeAh5aL8CmeZUXCwUxt2P0hfbcoCAiDc3SV8RzY0Z24xMyEVh5xB85FcbTixktRcw4nfXpw7WbfGTJeZfZUz6ZCmZSYE3qY9rx4ovvZSFO1zwhCNA66eLRaoYWMJWj+HtHrrkzhFZOhKmzsEkoedLp6lvyjUKhxidifXhpukj8n+6t3NvRcMxyGVjT0oC5ol4NeUUissxPaAcHRgAmRWo9/MMoAKZMHzjEBQHxd46BlvY3wcwCqjw0ISVVuFWbM5z9QU3Hs31h/5wu5Ew3m0+2DDcwlkAjcufW0RgDNSY0t8Q5vyTnPq9keXvp7FnBysdJ021F1jKUKAGr2P064jwJiLYIo7sgjnnp2H2mnnnk9nq1udfEluidU5+K235v3oyIY2Th+2WZrJPU90nYrxPnoX8UCvQcrzwwMtKMm/zMM9cCh9/X6Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
