appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: G0c8aUZ+t81TvJqQJWO+meK+9wIxeAxEF9qonNZGby6l1Qpeoswi25avEdYgn7j3QMncvYcR4+SWECL8fPTnvIxxEFhoGUBfoC/Gw9MpXIEyzBiFd2Co48zbuG7GBPt34zBm8CRyVin2UM9XBuVIxD6SCQqoN8l2pnNndqFy7ZU2AQIdpKKCBgvN34v/6MwKqL+RdANYYCyHZDsw+lcTJhy5W52IdqJ63Pm+N1daqEBLoVg78L2jCq5Aus+s2bfBH9yedfJa3Uzx4P4X6gm2hUrcfDRtbhR77F1wQfXCzB0xKgrcVqydQT+oOdcpb8Jqm8zUCzOTdDEChnKcST8hq8RXmEe6vmAaZAt7gUxd54vUl7jTO41nHugmEzdS4X2kTWnkbRyGzdGnoZY3KYrmUfDWZiWcleAg0qWiSJdWauBm7TxHKUgoJKfykLwTnvsDVw0wRWky3s84q0USXvaymHzJ4pg/t+XdHZpBtAx8GTEW+CLHq8v9BBzsMyonBYrpMtDXr1r7C6S80T18+VzKIjM09zeswfUqb42vXASlycN2VZQQESusaEk7bNpI6hVPlKpuImdmrMrKpfTAd2MmbMhLxT8p2lfTMELMQn/tZNr8vqLQAJAE1uH8/aOjwAiSXLO1VcvHxQ/RpxKXsCHQLpNlWU7PHKDBrgIarNbg4UY=}
